services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: npm run start:dev reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app

  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: npm run start:dev payments
    env_file:
      - ./apps/payments/.env
    ports:
      - '3003:3003'
    volumes:
      - .:/usr/src/app

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  prisma:
    build:
      context: .
      dockerfile: ./prisma/Dockerfile
      target: development
    command: npx prisma migrate deploy
    environment:
      - .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    

volumes:
  postgres-data:

